name: Deploy on Heroku

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: wokroll/names-app@main # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "names-app-sukhonos-docker" #Must be unique in Heroku
        heroku_email: "suhonos.p@gmail.com"
        
